### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by mnapoli** [stratifyphp/framework#2]
`application` or `kernel`?

Stratify is not intended to be a framework but rather building blocks to let users build their own architecture.

**Comment by EgorGruzdev** [comment]
Application

**Comment by wysow** [comment]
As the "main" piece of this seems to be the `Application` let's go for this I think...

**Comment by mnapoli** [comment]
The main thing this package provides is dependency injection + building of the middleware tree (with DI) + the module system.

The application class glues together:
- the PHP-DI kernel (for DI and modules)
- the stratify HTTP application (from the http package): https://github.com/stratifyphp/http/blob/master/src/Application.php
- the silly application (for CLI)

So to me "application" is very restrictive. Other stratify packages can be used, like Symfony components, to create our own framework/application from scratch.

This package provides a "framework" (in the original sense of the term): it's still up to you to decide your HTTP architecture with your middlewares, however some parts of the architecture are decided though (the dependency injection + modules part).

So I'm more with framework for now, even though there is less IoC and architecture in here than in other PHP frameworks.

**Comment by wysow** [comment]
OK let's stay with framework then... Your explanation is convincing...

**Comment by pocky** [comment]
Framework sounds good.

I don't like "Kernel" and writing the application is my job, not yours ;)

**Comment by mnapoli** [comment]
Closing for now

> writing the application is my job, not yours ;)

love that!
